package qupath.ext.dlclassifier.service;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.IOException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javafx.stage.Window;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import qupath.ext.dlclassifier.model.ClassifierMetadata;
import qupath.fx.dialogs.Dialogs;

/**
 * Saves and reloads Training Area Issues sessions for a given classifier.
 * <p>
 * A session pairs a snapshot of the per-tile evaluation results
 * ({@link ClassifierClient.TileEvaluationResult}) with copies of the PNG
 * assets rendered during evaluation. Sessions live under the classifier's
 * model directory so they travel with the model across projects and users:
 *
 * <pre>
 * &lt;modelDir&gt;/
 *   disagreement/                       # transient - latest run
 *   training_issues_sessions/
 *     &lt;sessionId&gt;/                    # yyyyMMdd_HHmmss
 *       session.json
 *       assets/
 *         &lt;stem&gt;_tile.png
 *         &lt;stem&gt;_loss.png
 *         &lt;stem&gt;_disagree.png
 * </pre>
 *
 * Each {@code session.json} captures the classifier's file size and
 * last-modified time so a reload after an in-place retrain can surface a
 * staleness warning ({@code ClassifierMetadata.id} is not regenerated by
 * retraining, so we cannot rely on the ID alone).
 */
public final class TrainingIssuesSessionStore {

    private static final Logger logger = LoggerFactory.getLogger(TrainingIssuesSessionStore.class);

    private static final String SESSIONS_DIRNAME = "training_issues_sessions";
    private static final String ASSETS_DIRNAME = "assets";
    private static final String MANIFEST_FILENAME = "session.json";
    private static final DateTimeFormatter SESSION_ID_FORMAT = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");
    private static final long SOFT_CAP_BYTES = 500L * 1024 * 1024;

    private static final Gson GSON =
            new GsonBuilder().setPrettyPrinting().serializeNulls().create();

    private TrainingIssuesSessionStore() {}

    // ==================== Public records ====================

    public record SaveEstimate(long totalBytes, int tileCount, Path targetDir) {}

    public record SessionInfo(
            Path dir,
            String sessionId,
            String savedAt,
            String note,
            int tileCount,
            boolean stale,
            String stalenessReason) {
        @Override
        public String toString() {
            String suffix = stale ? " (STALE: " + stalenessReason + ")" : "";
            String label = (note == null || note.isBlank()) ? sessionId : sessionId + " - " + note;
            return label + " [" + tileCount + " tiles]" + suffix;
        }
    }

    public record LoadedSession(
            List<ClassifierClient.TileEvaluationResult> results, double downsample, int patchSize, SessionInfo info) {}

    // ==================== Save ====================

    /**
     * Estimates disk usage for the PNG files referenced by the given results.
     * Missing files are skipped (contribute zero bytes) rather than raising.
     */
    public static SaveEstimate estimateSave(Path modelDir, List<ClassifierClient.TileEvaluationResult> results) {
        long totalBytes = 0L;
        int counted = 0;
        for (var r : results) {
            totalBytes += safeSize(r.tileImagePath());
            totalBytes += safeSize(r.lossHeatmapPath());
            totalBytes += safeSize(r.disagreementImagePath());
            counted++;
        }
        Path target = modelDir.resolve(SESSIONS_DIRNAME);
        return new SaveEstimate(totalBytes, counted, target);
    }

    /**
     * Shows a confirmation dialog (size + location, optional user note), then
     * saves. Returns the session directory on success, or null if the user
     * cancelled or an error occurred (errors are already surfaced to the UI).
     */
    public static Path saveWithConfirmation(
            Window owner,
            ClassifierMetadata metadata,
            Path modelDir,
            double downsample,
            int patchSize,
            List<ClassifierClient.TileEvaluationResult> results) {
        if (metadata == null || modelDir == null || results == null || results.isEmpty()) {
            Dialogs.showErrorMessage(
                    "Save Session", "Cannot save: missing classifier metadata, model directory, or results.");
            return null;
        }

        SaveEstimate est = estimateSave(modelDir, results);
        String mb = String.format("%.1f", est.totalBytes() / (1024.0 * 1024.0));
        String confirmText = String.format(
                "Save Training Area Issues session?%n%n"
                        + "Classifier: %s (id %s)%n"
                        + "Tiles: %d%n"
                        + "Estimated disk usage: %s MB%n"
                        + "Location:%n  %s%n%n"
                        + "Continue?",
                metadata.getName(), metadata.getId(), est.tileCount(), mb, est.targetDir());
        if (!Dialogs.showConfirmDialog("Save Training Area Issues", confirmText)) {
            return null;
        }

        if (est.totalBytes() > SOFT_CAP_BYTES) {
            String warn = String.format("This session will use about %s MB of disk space.%nContinue anyway?", mb);
            if (!Dialogs.showConfirmDialog("Large session size", warn)) {
                return null;
            }
        }

        String note =
                Dialogs.showInputDialog("Session note", "Optional note for this session (leave blank for none):", "");
        if (note == null) {
            return null;
        }

        try {
            Path dir = save(metadata, modelDir, downsample, patchSize, results, note);
            Dialogs.showInfoNotification("Training Area Issues", "Session saved to " + dir);
            return dir;
        } catch (Exception e) {
            logger.error("Failed to save Training Area Issues session", e);
            Dialogs.showErrorMessage("Save Session", "Failed to save session: " + e.getMessage());
            return null;
        }
    }

    /**
     * Writes the session to disk. Returns the session directory.
     *
     * @throws IOException if a filesystem operation fails
     */
    public static Path save(
            ClassifierMetadata metadata,
            Path modelDir,
            double downsample,
            int patchSize,
            List<ClassifierClient.TileEvaluationResult> results,
            String note)
            throws IOException {
        String sessionId = LocalDateTime.now().format(SESSION_ID_FORMAT);
        Path sessionDir = modelDir.resolve(SESSIONS_DIRNAME).resolve(sessionId);
        Path assetsDir = sessionDir.resolve(ASSETS_DIRNAME);
        Files.createDirectories(assetsDir);

        JsonObject manifest = new JsonObject();
        manifest.addProperty("schemaVersion", 1);
        manifest.addProperty("sessionId", sessionId);
        manifest.addProperty("savedAt", LocalDateTime.now().toString());
        manifest.addProperty("note", note == null ? "" : note);

        manifest.add("classifier", buildClassifierBlock(metadata, modelDir));

        JsonObject evaluation = new JsonObject();
        evaluation.addProperty("downsample", downsample);
        evaluation.addProperty("patchSize", patchSize);
        evaluation.addProperty("totalTiles", results.size());
        manifest.add("evaluation", evaluation);

        JsonArray tiles = new JsonArray();
        for (var r : results) {
            JsonObject t = new JsonObject();
            t.addProperty("filename", r.filename());
            t.addProperty("split", r.split());
            t.addProperty("loss", r.loss());
            t.addProperty("disagreementPct", r.disagreementPct());
            t.addProperty("meanIoU", r.meanIoU());

            JsonObject iou = new JsonObject();
            if (r.perClassIoU() != null) {
                for (Map.Entry<String, Double> e : r.perClassIoU().entrySet()) {
                    if (e.getValue() == null || Double.isNaN(e.getValue())) {
                        iou.add(e.getKey(), null);
                    } else {
                        iou.addProperty(e.getKey(), e.getValue());
                    }
                }
            }
            t.add("perClassIoU", iou);

            t.addProperty("x", r.x());
            t.addProperty("y", r.y());
            t.addProperty("sourceImage", r.sourceImage());
            t.addProperty("sourceImageId", r.sourceImageId());

            // Prefix each asset filename with the tile's split to mirror the
            // train/val subdir separation in <modelDir>/disagreement/. Without
            // this, two tiles with the same stem in different splits collapse
            // onto the same assets/<stem>.png and one split silently wins.
            String split = r.split() == null ? "" : r.split();
            String tileAsset = copyAsset(r.tileImagePath(), assetsDir, split);
            String lossAsset = copyAsset(r.lossHeatmapPath(), assetsDir, split);
            String disagreeAsset = copyAsset(r.disagreementImagePath(), assetsDir, split);
            String predAsset = copyAsset(r.predictionMapPath(), assetsDir, split);
            String confAsset = copyAsset(r.confidenceMapPath(), assetsDir, split);
            String gtAsset = copyAsset(r.groundTruthMaskPath(), assetsDir, split);
            t.addProperty("tileAsset", tileAsset);
            t.addProperty("lossAsset", lossAsset);
            t.addProperty("disagreeAsset", disagreeAsset);
            t.addProperty("predAsset", predAsset);
            t.addProperty("confAsset", confAsset);
            t.addProperty("gtAsset", gtAsset);

            JsonArray confusions = new JsonArray();
            if (r.topConfusions() != null) {
                for (ClassifierClient.ConfusionPair cp : r.topConfusions()) {
                    JsonObject p = new JsonObject();
                    p.addProperty("gt", cp.gt());
                    p.addProperty("pred", cp.pred());
                    p.addProperty("pixels", cp.pixels());
                    p.addProperty("gtTotal", cp.gtTotal());
                    confusions.add(p);
                }
            }
            t.add("topConfusions", confusions);

            // Per-class GT pixel counts: the confusion matrix's denominator.
            // Sessions written before this field existed have no such block, and
            // load() reads a missing one as "fall back to pair-derived totals".
            JsonObject gtTotals = new JsonObject();
            if (r.gtPixelTotals() != null) {
                for (Map.Entry<String, Long> e : r.gtPixelTotals().entrySet()) {
                    gtTotals.addProperty(e.getKey(), e.getValue());
                }
            }
            t.add("gtPixelTotals", gtTotals);

            t.addProperty("disagreementPixels", r.disagreementPixels());
            JsonArray hist = new JsonArray();
            if (r.disagreementConfHistogram() != null) {
                for (Integer bin : r.disagreementConfHistogram()) {
                    hist.add(bin == null ? 0 : bin);
                }
            }
            t.add("disagreementConfHistogram", hist);

            tiles.add(t);
        }
        manifest.add("tiles", tiles);

        Files.writeString(sessionDir.resolve(MANIFEST_FILENAME), GSON.toJson(manifest));
        logger.info("Saved Training Area Issues session: {}", sessionDir);
        return sessionDir;
    }

    // ==================== List / Load ====================

    /**
     * Lists all sessions saved under the given classifier's model directory,
     * newest first. Includes a staleness flag computed against the current
     * model file.
     */
    public static List<SessionInfo> listSessions(ClassifierMetadata metadata, Path modelDir) {
        List<SessionInfo> out = new ArrayList<>();
        Path sessionsRoot = modelDir.resolve(SESSIONS_DIRNAME);
        if (!Files.isDirectory(sessionsRoot)) {
            return out;
        }
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(sessionsRoot)) {
            for (Path dir : stream) {
                if (!Files.isDirectory(dir)) continue;
                Path manifestPath = dir.resolve(MANIFEST_FILENAME);
                if (!Files.exists(manifestPath)) continue;
                try {
                    JsonObject manifest = JsonParser.parseString(Files.readString(manifestPath))
                            .getAsJsonObject();
                    String id =
                            getString(manifest, "sessionId", dir.getFileName().toString());
                    String savedAt = getString(manifest, "savedAt", "");
                    String note = getString(manifest, "note", "");
                    int count = manifest.has("tiles")
                            ? manifest.getAsJsonArray("tiles").size()
                            : 0;
                    String stalenessReason = computeStaleness(manifest, metadata, modelDir);
                    boolean stale = stalenessReason != null && !stalenessReason.isEmpty();
                    out.add(new SessionInfo(dir, id, savedAt, note, count, stale, stalenessReason));
                } catch (Exception e) {
                    logger.warn("Skipping unreadable session {}: {}", dir, e.getMessage());
                }
            }
        } catch (IOException e) {
            logger.warn("Failed to scan sessions directory {}: {}", sessionsRoot, e.getMessage());
        }
        out.sort(Comparator.comparing(SessionInfo::sessionId).reversed());
        return out;
    }

    /**
     * Loads a session from disk and materializes a list of
     * {@link ClassifierClient.TileEvaluationResult} with paths rewritten to
     * absolute paths under the session's {@code assets/} directory.
     */
    public static LoadedSession load(Path sessionDir) throws IOException {
        Path manifestPath = sessionDir.resolve(MANIFEST_FILENAME);
        JsonObject manifest =
                JsonParser.parseString(Files.readString(manifestPath)).getAsJsonObject();

        JsonObject evaluation = manifest.getAsJsonObject("evaluation");
        double downsample = evaluation != null && evaluation.has("downsample")
                ? evaluation.get("downsample").getAsDouble()
                : 1.0;
        int patchSize = evaluation != null && evaluation.has("patchSize")
                ? evaluation.get("patchSize").getAsInt()
                : 512;

        List<ClassifierClient.TileEvaluationResult> results = new ArrayList<>();
        JsonArray tiles = manifest.has("tiles") ? manifest.getAsJsonArray("tiles") : new JsonArray();
        for (JsonElement el : tiles) {
            JsonObject t = el.getAsJsonObject();
            Map<String, Double> iouMap = new LinkedHashMap<>();
            if (t.has("perClassIoU") && t.get("perClassIoU").isJsonObject()) {
                JsonObject iou = t.getAsJsonObject("perClassIoU");
                for (Map.Entry<String, JsonElement> entry : iou.entrySet()) {
                    if (entry.getValue().isJsonNull()) continue;
                    iouMap.put(entry.getKey(), entry.getValue().getAsDouble());
                }
            }
            List<ClassifierClient.ConfusionPair> topConfusions = new ArrayList<>();
            if (t.has("topConfusions") && t.get("topConfusions").isJsonArray()) {
                JsonArray arr = t.getAsJsonArray("topConfusions");
                for (JsonElement pe : arr) {
                    if (pe == null || pe.isJsonNull()) continue;
                    JsonObject pp = pe.getAsJsonObject();
                    topConfusions.add(new ClassifierClient.ConfusionPair(
                            getString(pp, "gt", ""),
                            getString(pp, "pred", ""),
                            pp.has("pixels") ? pp.get("pixels").getAsLong() : 0L,
                            pp.has("gtTotal") ? pp.get("gtTotal").getAsLong() : 0L));
                }
            }

            Map<String, Long> gtPixelTotals = new LinkedHashMap<>();
            if (t.has("gtPixelTotals") && t.get("gtPixelTotals").isJsonObject()) {
                JsonObject totals = t.getAsJsonObject("gtPixelTotals");
                for (Map.Entry<String, JsonElement> entry : totals.entrySet()) {
                    if (entry.getValue().isJsonNull()) continue;
                    gtPixelTotals.put(entry.getKey(), entry.getValue().getAsLong());
                }
            }

            long disagreementPixels =
                    t.has("disagreementPixels") ? t.get("disagreementPixels").getAsLong() : 0L;
            List<Integer> disagreementHist = new ArrayList<>();
            if (t.has("disagreementConfHistogram")
                    && t.get("disagreementConfHistogram").isJsonArray()) {
                JsonArray hist = t.getAsJsonArray("disagreementConfHistogram");
                for (JsonElement be : hist) {
                    disagreementHist.add(be == null || be.isJsonNull() ? 0 : be.getAsInt());
                }
            }

            results.add(new ClassifierClient.TileEvaluationResult(
                    getString(t, "filename", ""),
                    getString(t, "split", ""),
                    t.has("loss") ? t.get("loss").getAsDouble() : 0.0,
                    t.has("disagreementPct") ? t.get("disagreementPct").getAsDouble() : 0.0,
                    iouMap,
                    t.has("meanIoU") ? t.get("meanIoU").getAsDouble() : 0.0,
                    t.has("x") ? t.get("x").getAsInt() : 0,
                    t.has("y") ? t.get("y").getAsInt() : 0,
                    getString(t, "sourceImage", ""),
                    getString(t, "sourceImageId", ""),
                    resolveAsset(sessionDir, t, "disagreeAsset"),
                    resolveAsset(sessionDir, t, "lossAsset"),
                    resolveAsset(sessionDir, t, "tileAsset"),
                    resolveAsset(sessionDir, t, "predAsset"),
                    resolveAsset(sessionDir, t, "confAsset"),
                    resolveAsset(sessionDir, t, "gtAsset"),
                    topConfusions,
                    disagreementPixels,
                    disagreementHist,
                    gtPixelTotals));
        }

        SessionInfo info = new SessionInfo(
                sessionDir,
                getString(manifest, "sessionId", sessionDir.getFileName().toString()),
                getString(manifest, "savedAt", ""),
                getString(manifest, "note", ""),
                results.size(),
                false,
                "");
        return new LoadedSession(results, downsample, patchSize, info);
    }

    // ==================== Helpers ====================

    private static JsonObject buildClassifierBlock(ClassifierMetadata metadata, Path modelDir) {
        JsonObject c = new JsonObject();
        c.addProperty("id", metadata.getId());
        c.addProperty("name", metadata.getName());
        if (metadata.getCreatedAt() != null) {
            c.addProperty("createdAt", metadata.getCreatedAt().toString());
        } else {
            c.add("createdAt", null);
        }
        c.addProperty("trainingEpochs", metadata.getTrainingEpochs());
        c.addProperty("finalLoss", metadata.getFinalLoss());
        c.addProperty("finalAccuracy", metadata.getFinalAccuracy());

        Path modelFile = firstExisting(modelDir.resolve("model.pt"), modelDir.resolve("model.onnx"));
        if (modelFile != null) {
            try {
                c.addProperty(
                        "modelFileModifiedAt",
                        LocalDateTime.ofInstant(
                                        Files.getLastModifiedTime(modelFile).toInstant(),
                                        java.time.ZoneId.systemDefault())
                                .toString());
                c.addProperty("modelFileSize", Files.size(modelFile));
                c.addProperty("modelFileName", modelFile.getFileName().toString());
            } catch (IOException e) {
                logger.debug("Could not stat model file {}: {}", modelFile, e.getMessage());
            }
        }
        return c;
    }

    private static String computeStaleness(JsonObject manifest, ClassifierMetadata metadata, Path modelDir) {
        if (!manifest.has("classifier")) return "";
        JsonObject saved = manifest.getAsJsonObject("classifier");
        String savedId = getString(saved, "id", "");
        if (metadata != null && !savedId.isEmpty() && !savedId.equals(metadata.getId())) {
            return "different classifier id";
        }

        Path modelFile = firstExisting(
                modelDir.resolve(getString(saved, "modelFileName", "model.pt")),
                modelDir.resolve("model.pt"),
                modelDir.resolve("model.onnx"));
        if (modelFile == null) return "";

        long savedSize = saved.has("modelFileSize") ? saved.get("modelFileSize").getAsLong() : -1;
        String savedMtime = getString(saved, "modelFileModifiedAt", "");
        try {
            long currentSize = Files.size(modelFile);
            String currentMtime = LocalDateTime.ofInstant(
                            Files.getLastModifiedTime(modelFile).toInstant(), java.time.ZoneId.systemDefault())
                    .toString();
            if (savedSize >= 0 && currentSize != savedSize) {
                return "model file size changed";
            }
            if (!savedMtime.isEmpty() && !savedMtime.equals(currentMtime)) {
                return "model file modified since save";
            }
        } catch (IOException e) {
            logger.debug("Staleness check could not stat {}: {}", modelFile, e.getMessage());
        }
        return "";
    }

    private static String copyAsset(String sourcePath, Path assetsDir, String split) throws IOException {
        if (sourcePath == null || sourcePath.isEmpty()) return null;
        Path src = Paths.get(sourcePath);
        if (!Files.exists(src)) return null;
        String base = src.getFileName().toString();
        // Prefix the asset filename with the split so a "stem_loss.png" from
        // train and one from val don't collide in the flat assets/ directory.
        // ASCII-only to stay Windows-safe.
        String filename = (split != null && !split.isEmpty()) ? split + "_" + base : base;
        Path dst = assetsDir.resolve(filename);
        Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING);
        return ASSETS_DIRNAME + "/" + filename;
    }

    private static String resolveAsset(Path sessionDir, JsonObject t, String key) {
        if (!t.has(key) || t.get(key).isJsonNull()) return null;
        String rel = t.get(key).getAsString();
        if (rel == null || rel.isEmpty()) return null;
        return sessionDir.resolve(rel).toAbsolutePath().toString();
    }

    private static Path firstExisting(Path... candidates) {
        for (Path p : candidates) {
            if (p != null && Files.exists(p)) return p;
        }
        return null;
    }

    private static long safeSize(String path) {
        if (path == null || path.isEmpty()) return 0L;
        try {
            Path p = Paths.get(path);
            if (Files.exists(p)) {
                return Files.size(p);
            }
        } catch (Exception ignored) {
            // best-effort
        }
        return 0L;
    }

    private static String getString(JsonObject obj, String key, String fallback) {
        if (obj == null || !obj.has(key) || obj.get(key).isJsonNull()) return fallback;
        return obj.get(key).getAsString();
    }
}
