package qupath.ext.dlclassifier.service;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

/**
 * Guards the two bundled pixi locks against the failure modes that make the
 * Python environment uninstallable for end users.
 * <p>
 * These are not style checks. Each one has already shipped:
 * <ul>
 *   <li><b>Source distributions.</b> A lock entry pointing at a {@code .tar.gz}
 *       rather than a wheel makes pixi build the package on the user's machine.
 *       On Windows that needs MSVC 14+, which nobody installing a QuPath
 *       extension has, and {@code pixi install} aborts -- so the environment
 *       cannot be created at all, on either variant. That is exactly what
 *       stringzilla 5.1.2 did: it publishes cp310/cp312/cp313/cp314 Windows
 *       wheels but for cp311 only win_arm64, and this environment pins Python
 *       3.11, so win-64 resolved to the sdist.</li>
 *   <li><b>Lock format version.</b> Appose runs a pinned pixi that reads lock
 *       format v6 and rejects v7. A lock regenerated by a hand-upgraded pixi
 *       breaks every user's install.</li>
 * </ul>
 */
class PixiLockIntegrityTest {

    private static final String RESOURCE_BASE = "/qupath/ext/dlclassifier/";

    /** Highest lock format the pixi bundled with Appose can read. */
    private static final int MAX_LOCK_VERSION = 6;

    /**
     * Matches a platform key inside {@code environments: default: packages:},
     * which sits at six spaces of indentation; its entries follow at the same
     * indent prefixed with "- ".
     */
    private static final Pattern PLATFORM = Pattern.compile("^ {6}(\\S+):\\s*$");

    private static String readLock(String name) throws IOException {
        try (InputStream in = PixiLockIntegrityTest.class.getResourceAsStream(RESOURCE_BASE + name)) {
            assertThat(in).as("%s must be bundled as a resource", name).isNotNull();
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    @ParameterizedTest
    @ValueSource(strings = {"pixi.lock", "pixi-gpu.lock"})
    void noPlatformResolvesToASourceDistribution(String lockName) throws IOException {
        String lock = readLock(lockName);

        List<String> offenders = new ArrayList<>();
        String platform = null;
        for (String line : lock.split("\\R")) {
            Matcher m = PLATFORM.matcher(line);
            if (m.matches()) {
                platform = m.group(1);
                continue;
            }
            if (!line.startsWith("      ")) {
                // Dedented out of the packages block; the flat package
                // definitions that follow are shared across platforms.
                platform = null;
            }
            String trimmed = line.strip();
            if (platform != null && trimmed.startsWith("- pypi:") && trimmed.endsWith(".tar.gz")) {
                offenders.add(platform + " -> " + trimmed.substring(trimmed.lastIndexOf('/') + 1));
            }
        }

        assertThat(offenders)
                .as(
                        "%s pins source distributions; these are compiled on the user's machine "
                                + "and fail on Windows without MSVC, aborting the whole install",
                        lockName)
                .isEmpty();
    }

    @ParameterizedTest
    @ValueSource(strings = {"pixi.lock", "pixi-gpu.lock"})
    void lockFormatIsReadableByTheBundledPixi(String lockName) throws IOException {
        String firstLine = readLock(lockName).split("\\R", 2)[0].strip();

        assertThat(firstLine)
                .as("%s should declare its lock format first", lockName)
                .startsWith("version:");
        int version = Integer.parseInt(firstLine.substring("version:".length()).strip());
        assertThat(version)
                .as("lock format v%d is rejected by the pixi Appose runs; regenerate with tools/regen-pixi-lock.sh")
                .isLessThanOrEqualTo(MAX_LOCK_VERSION);
    }

    @Test
    void bothVariantsPinTheSameStringzillaWheelPolicy() throws IOException {
        // The specific regression: cp311 + win-64 must land on a wheel.
        for (String lockName : List.of("pixi.lock", "pixi-gpu.lock")) {
            assertThat(readLock(lockName))
                    .as("%s must resolve stringzilla to a Windows wheel, not the sdist", lockName)
                    .contains("stringzilla-5.1.1-cp311-cp311-win_amd64.whl")
                    .doesNotContain("stringzilla-5.1.2.tar.gz");
        }
    }
}
